namespace Helix.SalesService.Domain.Dtos;

public record WholeSalesDispatchTransactionDto(int? referenceId,
 DateTime transactionDate,
  short? groupType,
  short? iOType,
  short? transactionType,
  int? warehouseNumber,
  int? currentReferenceId,
  string? currentCode,
  double? total,
  double? totalVat,
  double? netTotal,
  string? description,
  short? dispatchType,
  int? carrierReferenceId,
  string? carrierCode,
  int? driverReferenceId,
  string? driverFirstName,
  string? driverLastName,
  string? identityNumber,
  string? plaque,
  int? shipInfoReferenceId,
  string? shipInfoCode,
  string? speCode,
  short? dispatchStatus,
  short? isEDispatch,
  string? doCode,
  string? docTrackingNumber,
  short? isEInvoice,
  short? eDispatchProfileId,
  short? eInvoiceProfileId, string? employeeOid, List<WholeSalesDispatchTransactionLineDto> lines)
{
}
