namespace Helix.Go.Entity;

public class LG_PRODORD
{
	#region Properties 
	public int LOGICALREF { get; set; }
	public short FICHETYPE { get; set; }
	public string FICHENO { get; set; } = string.Empty;
	public DateTime? DATE_ { get; set; }
	public string GENEXP1 { get; set; } = string.Empty;
	public string GENEXP2 { get; set; } = string.Empty;
	public string GENEXP3 { get; set; } = string.Empty;
	public string GENEXP4 { get; set; } = string.Empty;
	public string GENEXP5 { get; set; } = string.Empty;
	public string GENEXP6 { get; set; } = string.Empty;
	public short? RELEASED { get; set; }
	public short CANCELLED { get; set; }
	public short? PRIORITY { get; set; }
	public short? METHOD { get; set; }
	public short? SCHEDULED { get; set; }
	public short? PARTIALDEL { get; set; }
	public short? DIFFWHOUSEUSE { get; set; }
	public short? AUTOMTRISSUE { get; set; }
	public short? REWORK { get; set; }
	public int? ROUTINGREF { get; set; }
	public int? MASTERREF { get; set; }
	public int? REVREF { get; set; }
	public short? FACTORYNR { get; set; }
	public string SPECODE { get; set; } = string.Empty;
	public string CYPHCODE { get; set; } = string.Empty;
	public int CLIENTREF { get; set; }
	public int? ACCOUNTREF { get; set; }
	public int? CENTERREF { get; set; }
	public int ITEMREF { get; set; }
	public int UOMREF { get; set; }
	public int? USETREF { get; set; }
	public double UINFO1 { get; set; }
	public double UINFO2 { get; set; }
	public double? UINFO3 { get; set; }
	public double? UINFO4 { get; set; }
	public double? UINFO5 { get; set; }
	public double? UINFO6 { get; set; }
	public double? UINFO7 { get; set; }
	public double? UINFO8 { get; set; }
	public double PLNAMOUNT { get; set; }
	public double ACTAMOUNT { get; set; }
	public DateTime? BEGDATE { get; set; }
	public DateTime? ENDDATE { get; set; }
	public DateTime? DUEDATE { get; set; }
	public DateTime? STOPDATE { get; set; }
	public DateTime? STARTDATE { get; set; }
	public DateTime? PLNBEGDATE { get; set; }
	public DateTime? PLNENDDATE { get; set; }
	public double PLNDURATION { get; set; }
	public DateTime? ACTBEGDATE { get; set; }
	public DateTime? ACTENDDATE { get; set; }
	public double ACTDURATION { get; set; }
	public short STATUS { get; set; }
	public double? STDMATERIALCOST { get; set; }
	public double? STDEQUIPTCOST { get; set; }
	public double? STDWSCOST { get; set; }
	public double? STDLABORCOST { get; set; }
	public double? STDOVERHCOST { get; set; }
	public double? STDTOTALCOST { get; set; }
	public double? STDMATERIALRPCOST { get; set; }
	public double? STDEQUIPTRPCOST { get; set; }
	public double? STDWSRPCOST { get; set; }
	public double? STDLABORRPCOST { get; set; }
	public double? STDOVERHRPCOST { get; set; }
	public double? STDTOTALRPCOST { get; set; }
	public double? ACTMATERIALCOST { get; set; }
	public double? ACTEQUIPTCOST { get; set; }
	public double? ACTWSCOST { get; set; }
	public double? ACTLABORCOST { get; set; }
	public double? ACTOVERHCOST { get; set; }
	public double? ACTTOTALCOST { get; set; }
	public double? ACTMATERIALRPCOST { get; set; }
	public double? ACTEQUIPTRPCOST { get; set; }
	public double? ACTWSRPCOST { get; set; }
	public double? ACTLABORRPCOST { get; set; }
	public double? ACTOVERHRPCOST { get; set; }
	public double? ACTTOTALRPCOST { get; set; }
	public short? APPROVED { get; set; }
	public short? ACTIVE { get; set; }
	public short? CAPIBLOCK_CREATEDBY { get; set; }
	public DateTime? CAPIBLOCK_CREADEDDATE { get; set; }
	public short? CAPIBLOCK_CREATEDHOUR { get; set; }
	public short? CAPIBLOCK_CREATEDMIN { get; set; }
	public short? CAPIBLOCK_CREATEDSEC { get; set; }
	public short? CAPIBLOCK_MODIFIEDBY { get; set; }
	public DateTime? CAPIBLOCK_MODIFIEDDATE { get; set; }
	public short? CAPIBLOCK_MODIFIEDHOUR { get; set; }
	public short? CAPIBLOCK_MODIFIEDMIN { get; set; }
	public short? CAPIBLOCK_MODIFIEDSEC { get; set; }
	public short? SITEID { get; set; }
	public short? RECSTATUS { get; set; }
	public int? ORGLOGICREF { get; set; }
	public int? WFSTATUS { get; set; }
	public short? NEEDRELEASE { get; set; }
	public short? NEEDPROCURE { get; set; }
	public short? PROCURED { get; set; }
	public int? BEGTIME { get; set; }
	public int? ENDTIME { get; set; }
	public int? PLNBEGTIME { get; set; }
	public int? PLNENDTIME { get; set; }
	public int? ACTBEGTIME { get; set; }
	public int? ACTENDTIME { get; set; }
	public short? PRINTCNT { get; set; }
	public short? STDACCOUNTED { get; set; }
	public short? ACTACCOUNTED { get; set; }
	public double? GROSSUINFO1 { get; set; }
	public double? GROSSUINFO2 { get; set; }
	public short? TEXTINC { get; set; }
	public short? CHKRESCAP { get; set; }
	public int? PROJECTREF { get; set; }
	public short? ADVICEWS { get; set; }
	public int? DUETIME { get; set; }
	public short? APPROVE { get; set; }
	public DateTime? APPROVEDATE { get; set; }
	public double? UFRSMATERIALCOST { get; set; }
	public double? UFRSEQUIPTCOST { get; set; }
	public double? UFRSWSCOST { get; set; }
	public double? UFRSLABORCOST { get; set; }
	public double? UFRSOVERHCOST { get; set; }
	public double? UFRSTOTALCOST { get; set; }
	public double? UFRSMATERIALRPCOST { get; set; }
	public double? UFRSEQUIPTRPCOST { get; set; }
	public double? UFRSWSRPCOST { get; set; }
	public double? UFRSLABORRPCOST { get; set; }
	public double? UFRSOVERHRPCOST { get; set; }
	public double? UFRSTOTALRPCOST { get; set; }
	public short? UFRSACCOUNTED { get; set; }
	public double? STDOVERHCOSTG1 { get; set; }
	public double? STDOVERHCOSTG2 { get; set; }
	public double? STDOVERHCOSTG3 { get; set; }
	public double? STDOVERHCOSTG4 { get; set; }
	public double? STDOVERHCOSTG5 { get; set; }
	public double? STDOVERHCOSTG6 { get; set; }
	public double? STDOVERHCOSTG7 { get; set; }
	public double? STDOVERHCOSTG8 { get; set; }
	public double? STDOVERHCOSTG9 { get; set; }
	public double? STDOVERHCOSTG10 { get; set; }
	public double? STDOVERHRPCOSTG1 { get; set; }
	public double? STDOVERHRPCOSTG2 { get; set; }
	public double? STDOVERHRPCOSTG3 { get; set; }
	public double? STDOVERHRPCOSTG4 { get; set; }
	public double? STDOVERHRPCOSTG5 { get; set; }
	public double? STDOVERHRPCOSTG6 { get; set; }
	public double? STDOVERHRPCOSTG7 { get; set; }
	public double? STDOVERHRPCOSTG8 { get; set; }
	public double? STDOVERHRPCOSTG9 { get; set; }
	public double? STDOVERHRPCOSTG10 { get; set; }
	public double? ACTOVERHCOSTG1 { get; set; }
	public double? ACTOVERHCOSTG2 { get; set; }
	public double? ACTOVERHCOSTG3 { get; set; }
	public double? ACTOVERHCOSTG4 { get; set; }
	public double? ACTOVERHCOSTG5 { get; set; }
	public double? ACTOVERHCOSTG6 { get; set; }
	public double? ACTOVERHCOSTG7 { get; set; }
	public double? ACTOVERHCOSTG8 { get; set; }
	public double? ACTOVERHCOSTG9 { get; set; }
	public double? ACTOVERHCOSTG10 { get; set; }
	public double? ACTOVERHRPCOSTG1 { get; set; }
	public double? ACTOVERHRPCOSTG2 { get; set; }
	public double? ACTOVERHRPCOSTG3 { get; set; }
	public double? ACTOVERHRPCOSTG4 { get; set; }
	public double? ACTOVERHRPCOSTG5 { get; set; }
	public double? ACTOVERHRPCOSTG6 { get; set; }
	public double? ACTOVERHRPCOSTG7 { get; set; }
	public double? ACTOVERHRPCOSTG8 { get; set; }
	public double? ACTOVERHRPCOSTG9 { get; set; }
	public double? ACTOVERHRPCOSTG10 { get; set; }
	public double? UFRSOVERHCOSTG1 { get; set; }
	public double? UFRSOVERHCOSTG2 { get; set; }
	public double? UFRSOVERHCOSTG3 { get; set; }
	public double? UFRSOVERHCOSTG4 { get; set; }
	public double? UFRSOVERHCOSTG5 { get; set; }
	public double? UFRSOVERHCOSTG6 { get; set; }
	public double? UFRSOVERHCOSTG7 { get; set; }
	public double? UFRSOVERHCOSTG8 { get; set; }
	public double? UFRSOVERHCOSTG9 { get; set; }
	public double? UFRSOVERHCOSTG10 { get; set; }
	public double? UFRSOVERHRPCOSTG1 { get; set; }
	public double? UFRSOVERHRPCOSTG2 { get; set; }
	public double? UFRSOVERHRPCOSTG3 { get; set; }
	public double? UFRSOVERHRPCOSTG4 { get; set; }
	public double? UFRSOVERHRPCOSTG5 { get; set; }
	public double? UFRSOVERHRPCOSTG6 { get; set; }
	public double? UFRSOVERHRPCOSTG7 { get; set; }
	public double? UFRSOVERHRPCOSTG8 { get; set; }
	public double? UFRSOVERHRPCOSTG9 { get; set; }
	public double? UFRSOVERHRPCOSTG10 { get; set; }
	public double? ROLLUPMATERIALCOST { get; set; }
	public double? ROLLUPEQUIPTCOST { get; set; }
	public double? ROLLUPWSCOST { get; set; }
	public double? ROLLUPLABORCOST { get; set; }
	public double? ROLLUPOVERHCOST { get; set; }
	public double? ROLLUPTOTALCOST { get; set; }
	public double? ROLLUPMATERIALRPCOST { get; set; }
	public double? ROLLUPEQUIPTRPCOST { get; set; }
	public double? ROLLUPWSRPCOST { get; set; }
	public double? ROLLUPLABORRPCOST { get; set; }
	public double? ROLLUPOVERHRPCOST { get; set; }
	public double? ROLLUPTOTALRPCOST { get; set; }
	public double? ROLLUPOVERHCOSTG1 { get; set; }
	public double? ROLLUPOVERHCOSTG2 { get; set; }
	public double? ROLLUPOVERHCOSTG3 { get; set; }
	public double? ROLLUPOVERHCOSTG4 { get; set; }
	public double? ROLLUPOVERHCOSTG5 { get; set; }
	public double? ROLLUPOVERHCOSTG6 { get; set; }
	public double? ROLLUPOVERHCOSTG7 { get; set; }
	public double? ROLLUPOVERHCOSTG8 { get; set; }
	public double? ROLLUPOVERHCOSTG9 { get; set; }
	public double? ROLLUPOVERHCOSTG10 { get; set; }
	public double? ROLLUPOVERHRPCOSTG1 { get; set; }
	public double? ROLLUPOVERHRPCOSTG2 { get; set; }
	public double? ROLLUPOVERHRPCOSTG3 { get; set; }
	public double? ROLLUPOVERHRPCOSTG4 { get; set; }
	public double? ROLLUPOVERHRPCOSTG5 { get; set; }
	public double? ROLLUPOVERHRPCOSTG6 { get; set; }
	public double? ROLLUPOVERHRPCOSTG7 { get; set; }
	public double? ROLLUPOVERHRPCOSTG8 { get; set; }
	public double? ROLLUPOVERHRPCOSTG9 { get; set; }
	public double? ROLLUPOVERHRPCOSTG10 { get; set; }
	public short? DOPLNRESERVE { get; set; }
	public short? ACTCOSTCALCULATED { get; set; }
	public short? HASPARALLELWSLOAD { get; set; }
	public string GUID { get; set; } = string.Empty;
	public short? CREATEWHFICHE { get; set; }
	public DateTime? PRINTDATE { get; set; }
	public short? DOSLPLNRESERVE { get; set; }
	#endregion
}
